@echo off
SET JUNCTION_BASE_PATH=%~dp0
echo %JUNCTION_BASE_PATH%

IF NOT EXIST %JUNCTION_BASE_PATH%AIModel ( mkdir %JUNCTION_BASE_PATH%AIModel )
mklink /j %JUNCTION_BASE_PATH%Debug\AIModel %JUNCTION_BASE_PATH%AIModel
mklink /j %JUNCTION_BASE_PATH%Release\AIModel %JUNCTION_BASE_PATH%AIModel
mklink /j %JUNCTION_BASE_PATH%MartianAI\AIModel %JUNCTION_BASE_PATH%AIModel
mklink /j %JUNCTION_BASE_PATH%MartianAIHost\AIModel %JUNCTION_BASE_PATH%AIModel
mklink /j %JUNCTION_BASE_PATH%MartianAICli\AIModel %JUNCTION_BASE_PATH%AIModel


IF NOT EXIST %JUNCTION_BASE_PATH%OutData ( mkdir %JUNCTION_BASE_PATH%OutData )
mklink /j %JUNCTION_BASE_PATH%Debug\OutData %JUNCTION_BASE_PATH%OutData
mklink /j %JUNCTION_BASE_PATH%Release\OutData %JUNCTION_BASE_PATH%OutData
mklink /j %JUNCTION_BASE_PATH%MartianAI\OutData %JUNCTION_BASE_PATH%OutData
mklink /j %JUNCTION_BASE_PATH%MartianAIHost\OutData %JUNCTION_BASE_PATH%OutData
mklink /j %JUNCTION_BASE_PATH%MartianAICli\OutData %JUNCTION_BASE_PATH%OutData
SET JUNCTION_BASE_PATH=
echo "done"
