set BUILD_CONFIGURATION=UnitTest_Debug
set BUILD_TARGET_ANY_CPU=false
set BUILD_TARGET_CPU=x64
set BUILD_TARGET_CPU_TEMP=
set BUILD_OPTION=rebuild

set MODULE_NAME=MartianAI
set UNIT_TEST_SOLUTION_NAME=MartianAI.UnitTest
set TARGET_UNIT_TEST_FILE_NAME=%UNIT_TEST_SOLUTION_NAME%
set TARGET_UNIT_TEST_FILE_NAME_SECOND=
set TARGET_UNIT_TEST_FILE_NAME_THIRD=
set TARGET_UNIT_TEST_FILE_NAME_FOURTH=
set TARGET_UNIT_TEST_FILE_NAME_FIFTH=
set TARGET_UNIT_TEST_FILE_NAME_SIXTH=

set OUTPUT_DIR=%BUILD_TARGET_CPU%\%BUILD_CONFIGURATION%

set ADDITIONAL_WORKSPACE=
set ADDITIONAL_ASSEMBLY_FILTERS=;-*unittest.dll;-*UnitTest.dll;-*\libiompstubs5md.dll;-*\libiomp5md.dll
set ADDITIONAL_FILE_FILTERS=;-C:\*;-c:\*;-*\h25_library\*;-*\H25_Library\*;-*martianAI\spdlog\include\*
set ADDITIONAL_CLASS_FILTERS=
set ADDITIONAL_TESTCASE_FILTER=

set ARTI_BRANCH=HME-US-CollaboBin/martianAI/unittest/250403_0008/
set ARTI_DOWNLOAD_TARGET_OTHER_PATH=%OUTPUT_DIR%

set ONEAPI_IPP_DLL_COPY=
set ONEAPI_MKL_DLL_COPY=