#pragma once

#define VOLUME_SIZE				    128			// Segmentation Volume Size
#define IN_IMAGE_SIZE				512			// StyleTransfer Image Size
#define FACECLASSIFICATION_IMAGE_SIZE				384			// FaceClassinfication Image Size

#define FETUSSEG_IN_VOLUME_SIZE				256
#define FETUSSEG_OUT_VOLUME_SIZE			256
#define CNSSEG_IN_VOLUME_SIZE				256
#define CNSSEG_OUT_VOLUME_SIZE				128
#define ST_INFERENCE_IMAGE_SIZE				512
#define NTSEG_IN_VOLUME_SIZE                256
#define NTSEG_IN_VOLUME_HEAD_SIZE           224
#define NTSEG_OUT_VOLUME_SIZE               128
#define NT2DSEG_IMAGE_SIZE				    256

// Connected Component Labeling
#define CCL_CONNECTIVITY_26     26
#define CCL_CONNECTIVITY_18     18
#define CCL_CONNECTIVITY_6      6
#define MAX_COMPONENTS          20 // Maximum number of components in each label
#define MAX_VOLUME_SIZE         20000

#define NUM_LABEL_CNS           8
#define NUM_LABEL_NT            6

enum MARTIAN_INFERERNCE_MODE
{
    MARTIAN_SEG_FETUS_1ST = 10,
    MARTIAN_SEG_FETUS_2ND,
    MARTIAN_STYLE_TRANSFER_INPAINTING = 20,
    MARTIAN_STYLE_TRANSFER_AUTORESTORE,
    MARTIAN_STYLE_TRANSFER_ENHANCEMENT,
    MARTIAN_STYLE_TRANSFER_FACECLASSIFICATION,
    MARTIAN_CNS_SEG = 30,
    MARTIAN_CNS_MEASURETC = 31,
    MARTIAN_CNS_MEASURETT,
    MARTIAN_CNS_MEASURETV,
    MARTIAN_SEG_NT = 40,
    MARTIAN_SEG_NTMEASURE,
    MARTIAN_SEG_PELVICASSIST = 60,
    MARTIAN_SEG_PELVICMEASURE,
    MARTIAN_3DPROC_GAUSSION = 110,
    MARTIAN_3DPROC_DILATION,
    MARTIAN_3DPROC_EROSION,
    MARTIAN_PROC_PCA = 120
};

enum ReturnError {
    RET_OK = 0,
    RET_FAILURE = -1,
    RET_CHECK_ERROR_CODE = -2
};
